pid: /tmp/pids/tmp/thin.pid
timeout: 30
wait: 30
log: /home/deployer/apps/gitboard/current/log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
daemonize: true
socket: /tmp/sockets/thin.sock
chdir: /home/deployer/apps/gitboard/current
tag: gitboard
