pid: /home/ubuntu/apps/gitboard/current/tmp/pids/thin.pid
timeout: 30
wait: 30
log: /home/ubuntu/apps/gitboard/current/log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
daemonize: true
socket: /home/ubuntu/apps/gitboard/current/tmp/sockets/thin.sock
chdir: /home/ubuntu/apps/gitboard/current
tag: gitboard
